#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# DefTree documentation build configuration file, created by
# sphinx-quickstart on Sun Oct  2 12:21:40 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('../..'))
import deftree
# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.coverage'
]
html_sidebars = {'**': ['globaltoc.html']}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

source_suffix = '.rst'

# The encoding of source files.
#
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

using = "using"
api = "api"
changelog = "changelog_link"
design = "design"

# General information about the project.
project = 'DefTree'
copyright = '2018, mattias.hedberg'
author = 'mattias.hedberg'

# The short X.Y version.
version = deftree.__version__
# The full version, including alpha/beta/rc tags.
release = deftree.__version__


language = None

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#
add_module_names = True

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'
if not on_rtd:  # only import and set the theme if we're building docs locally
    # html_theme = 'alabaster'
    html_theme = 'sphinx_rtd_theme'


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {'navigation_depth': 1}

html_static_path = ['_static']

html_show_sourcelink = False

htmlhelp_basename = 'DefTreedoc'

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'DefTree.tex', 'DefTree Documentation',
     'mattias.hedberg', 'manual'),
]

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'deftree', 'DefTree Documentation',
     [author], 1),
    (api, 'API', 'DefTree API',
     [author], 2),
    (using, 'Using', 'Using DefTree',
     [author], 3),
    (design, 'Design', 'Design',
     [author], 4),
    (changelog, 'Changelog', 'Changelog for DefTree',
     [author], 5)
]

# If true, show URL addresses after external links.
#
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'DefTree', 'DefTree Documentation',
     author, 'DefTree', 'Python interface for Defold files.',
     'Miscellaneous'),
]
